---
- name: ACL Configuration
  hosts: Branch2
  become_method: enable
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Inbound Config ACL
      ios_config:
        lines:
          - ip access-group 110 in
        parents: interface FastEthernet0/0

    - name: ACL Rules
      ios_config:
        lines:
          - access-list 110 deny icmp any any echo-reply
          - access-list 110 permit ip any any
        before: no access-list 110
        match: exact

##Ortua, Vyanne Joyce P.